let fakeTableData = [
  {
    id: "1",
    name: "John",
    email: "john34@outlook.com",
    phone: "+884870025",
    totalScan: 4,
    totalSchedule: 3,
    status: "active",
    role: "Moderator",
    lastLogin: "3 minutes ago",
  },
  {
    id: "2",
    name: "Emma",
    email: "emma34@outlook.com",
    phone: "+88457526",
    totalScan: 6,
    totalSchedule: 5,
    status: "active",
    role: "Editor",
    lastLogin: "2 minutes ago",
  },
  {
    id: "3",
    name: "Rachel",
    email: "rachel34@outlook.com",
    phone: "+88423526",
    totalScan: 2,
    totalSchedule: 4,
    status: "active",
    role: "Moderator",
    lastLogin: "3 minutes ago",
  },
];
